name: Deploy to IIS via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Zip website files
      run: zip -r site.zip . -x "*.git*"

    - name: Install SSH client
      run: sudo apt-get install -y openssh-client

    - name: Upload zip to EC2
      run: |
        echo "${{ secrets.IIS_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        scp -i private_key.pem -o StrictHostKeyChecking=no site.zip ${{ secrets.IIS_USERNAME }}@${{ secrets.IIS_HOST }}:C:/temp/site.zip

    - name: Deploy via PowerShell over SSH
      run: |
        ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.IIS_USERNAME }}@${{ secrets.IIS_HOST }} powershell -Command "
          Stop-Website -Name 'Personal Website' -ErrorAction SilentlyContinue;
          Expand-Archive -Path 'C:\temp\site.zip' -DestinationPath 'C:\inetpub\wwwroot' -Force;
          Start-Website -Name 'Personal Website'"
