name: Deploy to IIS via WinRM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Zip website files
      run: Compress-Archive -Path * -DestinationPath site.zip -Force -Exclude .git, .github
      shell: powershell

    - name: Deploy to IIS via WinRM
      uses: EnricoMi/publish-unit-test-result-action/download-artifact@v2
      with:
        name: site.zip
        path: site.zip
        
    - name: Deploy to Windows Server
      uses: Amadevus/pwsh-script@v2
      with:
        script: |
          $password = ConvertTo-SecureString "${{ secrets.IIS_PASSWORD }}" -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential("${{ secrets.IIS_USERNAME }}", $password)
          
          $session = New-PSSession -ComputerName ${{ secrets.IIS_HOST }} -Credential $credential -UseSSL:$false -Port 5985 -Authentication Negotiate
          
          # Copy the zip file to the remote server
          Copy-Item -Path "site.zip" -Destination "C:\temp\site.zip" -ToSession $session
          
          # Execute commands on the remote server
          Invoke-Command -Session $session -ScriptBlock {
            # Stop the website
            Stop-Website -Name 'Personal Website' -ErrorAction SilentlyContinue
            
            # Extract the zip file to the web root
            Expand-Archive -Path 'C:\temp\site.zip' -DestinationPath 'C:\inetpub\wwwroot\PersonalWebsite' -Force
            
            # Start the website
            Start-Website -Name 'Personal Website'
          }
          
          # Close the session
          Remove-PSSession -Session $session
